/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "main.h"
#include "bsp.h"

int main()
{
	SystemCoreClockUpdate();
	// Initialize LED & Button pin
	LED_Init();
	Button_Init();

	// Initialize Debug Console
	USART2_Init();
	my_printf("Console ready!\r\n");
	my_printf("SYSCLK = %d Hz\r\n", SystemCoreClock);

	I2C3_Init();

	// Start I2C transaction
	I2C3->CR2 |= I2C_CR2_START;
	// Main loop
	while(1)
	{
	}
}
