/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "bsp.h"

int main()
{
	SystemCoreClockUpdate();
	LED_Init();
	Button_Init();
	while(1){
		if (Button_Get_State() == 1) {
			LED_On();
		}
		else {
			LED_Off();
		}
	}
}
